name: Build & Test

on:
  push:
  schedule:
  - cron:  '0 3 * * 1'


jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        pip install . pytest
    - name: Test with pytest
      run: |
        make test
